import { Download, FileJson, FileSpreadsheet, FileText } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { api } from '../lib/api';
import type { Report } from '../lib/types';
import { Card } from '../components/ui/Card';
import { DataTable } from '../components/ui/DataTable';

export default function ReportsPage({ reports }: { reports: Report[] }) {
  const { t } = useTranslation();

  const formats = [
    { label: 'JSON', value: 'json', icon: <FileJson size={16} /> },
    { label: 'CSV', value: 'csv', icon: <FileSpreadsheet size={16} /> },
    { label: 'Excel', value: 'excel', icon: <FileSpreadsheet size={16} /> },
    { label: 'PDF', value: 'pdf', icon: <FileText size={16} /> },
    { label: 'GeoJSON', value: 'geojson', icon: <Download size={16} /> },
  ];

  return (
    <div className="space-y-4">
      <Card title={t('reports_page.engine_title')} eyebrow={t('reports_page.engine_eyebrow')}>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
          {formats.map((format) => (
            <a className="secondary-button" href={api.reportUrl(format.value)} key={format.value}>
              {format.icon}
              {format.label}
            </a>
          ))}
        </div>
      </Card>
      <Card title={t('reports_page.recent_title')} eyebrow={t('reports_page.recent_eyebrow')}>
        {reports.length ? (
          <DataTable columns={['name', 'slug', 'description']} rows={reports.map((report) => ({ name: report.name, slug: report.slug, description: report.description ?? 'Generated by La Olla de Datos' }))} />
        ) : (
          <div className="surface-muted p-4 text-sm text-steel-300">{t('reports_page.empty')}</div>
        )}
      </Card>
    </div>
  );
}
